nx: 200
ny: 200
time_steps: 100
dx: 1e-9
dy: 1e-9
# PML
use_pml: true
pml_thickness: 20
# TFSF
use_tfsf: false
tfsf_thickness: 10
# Polarizatrion
polarization: 'TM'
# Source plane_wave
# # source_type: 'plane_wave'
# # frequency: 5e15
# # function: 'gaussian'
# # plane_x1 : 97
# # plane_x2 : 103
# # plane_y1 : 30
# # plane_y2 : 150
# Source point
source_type: 'point_source'
source_x: 100
source_y: 100