# Simulation parameters
nx: 60
ny: 60
time_steps: 50
dx: 0.01
dy: 0.01
polarization: 'TE'

# PML parameters
use_pml: True
pml_thickness: 20

# TFSF parameters
use_tfsf: False
tfsf_thickness: 10

# Source parameters
function: 'sinusoidal'
frequency: 1500e6  #1.99862e14
source_type: 'point_source'

# Line source parameters
line_x: 20
line_y1: 40
line_y2: 60

# Point source parameters (if source_type is changed to 'point_source')
source_x: 30
source_y: 30